FIELD_NAMES = {
    "20": "Documentary Credit No.",
    "21": "Receiver's Reference",
    "23": "Reference to Pre-Advice",
    "26E": "Number of Amendments",
    "27": "Sequence of Total",
    "30": "Date Contract Agreed/Amended",
    "31C": "Issue Date",
    "31D": "Date and Place of Expiry",
    "31E": "Maturity Date",
    "32B": "Currency / Amount",
    "39A": "Percentage of Credit Amount Tolerance",
    "39B": "Maximum Credit Amount",
    "39C": "Additional Amounts Covered",
    "40A": "Form of Credit",
    "40E": "Applicable Rules for LC",
    "41A": "Credit Available With ... By ...",
    "41D": "Credit Available With ... By ...",
    "42A": "Drawee",
    "42C": "Drafts At",
    "42D": "Drawee",
    "42M": "Mixed Payment Details",
    "42P": "Deferred Payment Details",
    "43P": "Partial Shipments",
    "43T": "Transhipment",
    "44A": "Loading on Board / Dispatch / Taking Charge At",
    "44B": "For Transport To",
    "44C": "Latest Date for Shipment",
    "44D": "Shipment Period",
    "44E": "Port of Loading",
    "44F": "Port of Discharge",
    "45": "Goods",
    "45A": "Description of Goods and/or Services",
    "46": "Documents Required",
    "46A": "Documents Required",
    "47": "Additional Conditions",
    "47A": "Additional Conditions",
    "47B": "Additional Conditions",
    "48": "Period for Presentation of Documents",
    "49": "Confirmation Instructions",
    "50": "Applicant / Ordering Customer",
    "51A": "Applicant Bank",
    "51D": "Sending Institution",
    "53A": "Reimbursing Bank",
    "53D": "Reimbursement",
    "57A": "Advise Through Bank",
    "57D": "Account With Bank",
    "59": "Beneficiary",
    "71D": "Details of Charges",
    "72": "Sender to Receiver Information",
    "72Z": "Sender to Receiver Information / Additional Narrative",
    "78": "Instructions to Pay/Accept/Negotiating Bank",
    "79": "Narrative",
}